### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by ajp8164** [MuhammedKpln/react-native-chatty#24]
Thanks for this project!
Spending a lot of time debugging gifted chat  - looking at alternatives..

**Comment by MuhammedKpln** [comment]
Not fully active, currently only bug fixes if any.

**Comment by ajp8164** [comment]
Appreciate your reply!
I cloned and tried to run the example. Didn't  get it working. Can you please check this and offer a remedy? Seems like it's  environmental but I haven't seen this error before.
![Simulator Screen Shot - iPhone 14 - 2023-04-01 at 13 05 20](https://user-images.githubusercontent.com/1063765/229304661-056abe9a-d75c-4448-9016-fa128716ddbc.png)

EDIT: I also cut/paste your doc sample code and  found it doesn't match the implementation fully.
EDIT2: I really like the features you have. If  I can  get some  traction testing it and the performance is good I may  be able to contribute. Gifted Chat is a beast  and I always  have  trouble - especially performance.

**Comment by shivkr6** [comment]
@ajp8164 Were you able to fix it?
